// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVHrMRdEEnZoXRXvi8XthRGrdgfBbunWE',
    appId: '1:835742504751:web:0373f0b701890b39ccf3da',
    messagingSenderId: '835742504751',
    projectId: 'auth-319ed',
    authDomain: 'auth-319ed.firebaseapp.com',
    storageBucket: 'auth-319ed.firebasestorage.app',
    measurementId: 'G-M7BM0K6T5V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBswfWm8dOV8mYoH_b1apb-OV2ysmBJZoQ',
    appId: '1:835742504751:android:4cbcf47d3fc14beaccf3da',
    messagingSenderId: '835742504751',
    projectId: 'auth-319ed',
    storageBucket: 'auth-319ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6fjatywkRwLSsHopGssthin5pT8F_XxA',
    appId: '1:835742504751:ios:880d2b16b0801de9ccf3da',
    messagingSenderId: '835742504751',
    projectId: 'auth-319ed',
    storageBucket: 'auth-319ed.firebasestorage.app',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6fjatywkRwLSsHopGssthin5pT8F_XxA',
    appId: '1:835742504751:ios:880d2b16b0801de9ccf3da',
    messagingSenderId: '835742504751',
    projectId: 'auth-319ed',
    storageBucket: 'auth-319ed.firebasestorage.app',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVHrMRdEEnZoXRXvi8XthRGrdgfBbunWE',
    appId: '1:835742504751:web:51b12be96480426cccf3da',
    messagingSenderId: '835742504751',
    projectId: 'auth-319ed',
    authDomain: 'auth-319ed.firebaseapp.com',
    storageBucket: 'auth-319ed.firebasestorage.app',
    measurementId: 'G-SCEY4TYY41',
  );
}
